### ISSUE TITLE
ANS summary slide

### ISSUE THREAD

**Issue by katyhuff** [arfc/2018-07-27-cyclus-call#3]
Please add a slide describing :

- the current predicting the past work you're working on
- how's it going to work
- when will it be ready
- what kinds of questions will it answer
- where is the repo

**Comment by gwenchee** [comment]
@katyhuff should i create a section in the presentation tex file for predicting the past, or should this be included in transition scenarios?

**Comment by katyhuff** [comment]
Please put it in transition scenarios.

**Comment by katyhuff** [comment]
closed with #7
